# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'GPlaceAPIExample-Swift' do

use_frameworks!
pod 'Alamofire', '~> 1.3'

end

target 'GPlaceAPIExample-SwiftTests' do

end

